version: '3.3'
services:
   thumbor:
     container_name: EPG_thumbor
     image: apsl/thumbor:6.6.0
     volumes:
       - "${PHOTO_DIR}:/mydata"
       - ./config/thumbor/imaging.py:/usr/local/lib/python2.7/site-packages/thumbor/handlers/imaging.py
     environment:
       - FILE_LOADER_ROOT_PATH=/mydata/
       - LOADER=thumbor.loaders.file_loader
       - RESULT_STORAGE_STORES_UNSAFE=True
       - STORAGE=thumbor.storages.no_storage
       - SECURITY_KEY=EPG_SECRET_WHATSOEVER
       #- ALLOW_UNSAFE_URL=True
     restart: always

   php:
     container_name: EPG_php
     depends_on:
       - thumbor
       - mongodb
     build: ./config/php
     volumes:
     - "${PHOTO_DIR}:/mydata"
     restart: always
     links:
       - thumbor
     ports:
       - "${APP_PORT}:80"

   mongodb:
     container_name: EPG_mongodb
     image: mongo
     environment:
      MONGO_INITDB_ROOT_USERNAME: easyphpgallery
      MONGO_INITDB_ROOT_PASSWORD: easyphpgallery

