version: '2.0'
services:
   thumbor:
     #name: phpgallery_thumbor
     image: apsl/thumbor
     ports:
       - "180:8000"
     volumes:
       - ${PHOTO_DIR}:/data
     environment:
       - FILE_LOADER_ROOT_PATH=/data/
       - LOADER=thumbor.loaders.file_loader
     restart: always

   php:
     #name: phpgallery_php
     depends_on:
       - thumbor
     image: php:7.1-apache
     ports:
       - "${APP_PORT}:80"
     volumes:
     - .:/var/www/html
     - ${PHOTO_DIR}:/var/www/html/data
     restart: always
     links:
       - thumbor
