version: '2.0'
services:
   thumbor:
     #name: phpgallery_thumbor
     image: apsl/thumbor
     volumes:
       - ${PHOTO_DIR}:/mydata
     environment:
       - FILE_LOADER_ROOT_PATH=/mydata/
       - LOADER=thumbor.loaders.file_loader
       - RESULT_STORAGE_STORES_UNSAFE=True
       - STORAGE=thumbor.storages.no_storage
     restart: always

   php:
     #name: phpgallery_php
     depends_on:
       - thumbor
     image: php:7.1-apache
     volumes:
     - .:/var/www/html
     - ${PHOTO_DIR}:/mydata
     restart: always

   nginx:
     #name: phpgallery_nginx
     depends_on:
       - php
     image: nginx:stable-alpine
     ports:
       - "${APP_PORT}:80"
     volumes:
       - ./confnginx:/etc/nginx/conf.d
     restart: always
     links:
       - thumbor
       - php
