version: '2.0'
services:
   thumbor:
     #name: phpgallery_thumbor
     image: apsl/thumbor:6.3.0
     #build: ./config/thumbor
     volumes:
       - "${PHOTO_DIR}:/mydata"
       - ./config/thumbor/imaging.py:/usr/local/lib/python2.7/site-packages/thumbor/handlers/imaging.py
     ports:
       - 8001:8000
     environment:
       - FILE_LOADER_ROOT_PATH=/mydata/
       - LOADER=thumbor.loaders.file_loader
       - RESULT_STORAGE_STORES_UNSAFE=True
       - STORAGE=thumbor.storages.no_storage
     restart: always

   php:
     #name: phpgallery_php
     depends_on:
       - thumbor
     #image: php:7.1-apache
     build: ./config/php
     volumes:
     - "${PHOTO_DIR}:/mydata"
     restart: always

   nginx:
     #name: phpgallery_nginx
     depends_on:
       - php
     image: nginx:stable-alpine
     ports:
       - "${APP_PORT}:80"
     volumes:
       - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
     restart: always
     links:
       - thumbor
       - php
